CREATE TABLE [STOCK_SUCURSAL](
	[IdSucursal] [int] NOT NULL,
	[IdStock] [bigint] NOT NULL,
	[Unity] [int] NOT NULL,
	 CONSTRAINT FK_STOCK_SUCURSAL_SUCURSAL FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL(ID),
	 CONSTRAINT FK_STOCK_SUCURSAL_STOCK FOREIGN KEY (IdStock) REFERENCES STOCK(ID)
)

