CREATE TABLE [SALE_STOCK](
	[IdSale] [int] NOT NULL,
	[IdStock] [BigINT] NOT NULL
	 CONSTRAINT FK_SALE_STOCK_SALE_STATE FOREIGN KEY (IdSale) REFERENCES SALE(ID),
	 CONSTRAINT FK_SALE_STOCK_STOCK FOREIGN KEY (IdStock) REFERENCES STOCK(ID)
)

