CREATE TABLE [dbo].[RULES_PERMISSION](
	[IdRule] [int] NOT NULL,
	[IdPermission] [int] NOT NULL,
	[Read] [int] NOT NULL,
	[Write] [int] NOT NULL,
	 CONSTRAINT FK_RULES_PERMISSION_RULES FOREIGN KEY (IdRule) REFERENCES RULES(ID),
	 CONSTRAINT FK_RULES_PERMISSION_PERMISSION FOREIGN KEY (IdPermission) REFERENCES PERMISSION(ID)
)
