

CREATE TABLE [dbo].[ImpresorasADemanda](
	[IdImpresoraADemanda] [int] NOT NULL,
 CONSTRAINT [PK_ImpresorasADemanda] PRIMARY KEY CLUSTERED 
(
	[IdImpresoraADemanda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


