INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(1,'Pendiente','PE')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(2,'Impreso','IM')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(3,'Cancelado','CA')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(4,'Error','ER')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(5,'Imprmiendo','IP')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(6,'Residual','RE')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(7,'No Iniciado','NI')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(8,'ErrorGenerico','EG')
INSERT INTO EstadoImpresion (IdEstadoImpresion,Descripcion,Codigo) VALUES(9,'Redirect','RD')
